"""Inicial

Revision ID: 26882eaa1f7b
Revises: 5e187433ee60
Create Date: 2025-02-18 11:15:23.192458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26882eaa1f7b'
down_revision = '5e187433ee60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('fecha_inscripcion', sa.Date(), nullable=False),
    sa.Column('membresia_vencimiento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alumno')
    # ### end Alembic commands ###
